// On Windows with non-100% display scaling, devicePixelRatio is fractional
// (e.g. 1.25, 1.5). Chart.js sizes the canvas backing store against that
// fractional ratio, and sub-pixel rounding causes it to re-detect a "resize"
// every frame -> infinite redraw loop. Rounding to a whole number fixes it.
if (window.Chart) {
    Chart.defaults.devicePixelRatio = Math.round(window.devicePixelRatio) || 1;
}

const CATEGORY_COLORS = {
    'Languages':     { light: '#2a78d6', dark: '#3987e5' },
    'Cloud & Infra': { light: '#eb6834', dark: '#d95926' },
    'Data & AI':     { light: '#1baf7a', dark: '#199e70' }
};

const charts = [];

document.addEventListener('DOMContentLoaded', () => {
    // Read the processed JSON file generated by your Python backend script
    fetch('../backend/data/tech_trends.json')
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response error. Make sure your local server spans both directories.');
            }
            return response.json();
        })
        .then(jsonData => {
            // Update the UI timestamp string
            document.getElementById('timestamp').innerText = `Last updated: ${jsonData.last_updated}`;

            // Build individual metrics charts safely
            charts.push(createChart('languagesChart', jsonData.data['Languages'], 'Languages'));
            charts.push(createChart('cloudChart', jsonData.data['Cloud & Infra'], 'Cloud & Infra'));
            charts.push(createChart('dataChart', jsonData.data['Data & AI'], 'Data & AI'));
        })
        .catch(error => {
            console.error('Error loading dynamic metrics:', error);
            document.getElementById('timestamp').innerText = 'Error loading trending data.';
        });
});

function isDarkMode() {
    return window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
}

function chartTheme() {
    return isDarkMode()
        ? { ink: '#c3c2b7', grid: '#2c2c2a', axis: '#383835' }
        : { ink: '#52514e', grid: '#e1e0d9', axis: '#c3c2b7' };
}

function createChart(canvasId, categoryData, categoryKey) {
    const canvas = document.getElementById(canvasId);
    if (!canvas) return null;

    const ctx = canvas.getContext('2d');
    const theme = chartTheme();
    const barColor = CATEGORY_COLORS[categoryKey][isDarkMode() ? 'dark' : 'light'];

    // Sort items descending based on active job volume count
    const sorted = [...categoryData].sort((a, b) => b.value - a.value);
    const labels = sorted.map(item => item.name);
    const dataValues = sorted.map(item => item.value);

    return new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Active job postings',
                data: dataValues,
                backgroundColor: barColor,
                borderRadius: 4,
                borderSkipped: false,
                maxBarThickness: 28
            }]
        },
        options: {
            indexAxis: 'y', // Generates horizontal bar charts for clean text scanning
            responsive: true,
            maintainAspectRatio: false, // The .chart-wrapper element controls actual height
            layout: {
                padding: { right: 12 }
            },
            plugins: {
                legend: { display: false },
                tooltip: {
                    callbacks: {
                        label: (item) => `${item.formattedValue} job postings`
                    }
                }
            },
            scales: {
                x: {
                    beginAtZero: true,
                    grid: { color: theme.grid },
                    border: { color: theme.axis },
                    ticks: { color: theme.ink }
                },
                y: {
                    grid: { display: false },
                    border: { color: theme.axis },
                    ticks: { color: theme.ink }
                }
            }
        }
    });
}

// React to the viewer switching OS-level light/dark mode without a page reload
if (window.matchMedia) {
    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => {
        const theme = chartTheme();
        charts.forEach(chart => {
            if (!chart) return;
            const categoryKey = Object.keys(CATEGORY_COLORS).find(key =>
                CATEGORY_COLORS[key].light === chart.data.datasets[0].backgroundColor ||
                CATEGORY_COLORS[key].dark === chart.data.datasets[0].backgroundColor
            );
            chart.data.datasets[0].backgroundColor = CATEGORY_COLORS[categoryKey][isDarkMode() ? 'dark' : 'light'];
            chart.options.scales.x.grid.color = theme.grid;
            chart.options.scales.x.border.color = theme.axis;
            chart.options.scales.x.ticks.color = theme.ink;
            chart.options.scales.y.border.color = theme.axis;
            chart.options.scales.y.ticks.color = theme.ink;
            chart.update();
        });
    });
}
